//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraProjekt
{


    public partial class LogInScreen
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// tbEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox tbEmail;

        /// <summary>

        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<
        protected global::System.Web.UI.WebControls.TextBox tbPass;

        /// <summary>
        /// tbRepeatedPass control.

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanCheckUser;

        /// <summary>
        /// lblCheckUser control.

        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>

        protected global::System.Web.UI.WebControls.TextBox tbRepeatedPass;

        /// <summary>
        /// tbUserName control.

        protected global::System.Web.UI.WebControls.Label lblCheckUser;

        /// <summary>
        /// tbPass control.

        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>

        protected global::System.Web.UI.WebControls.TextBox tbUserName;

        /// <summary>
        /// btnRegister control.

        protected global::System.Web.UI.WebControls.TextBox tbPass;

        /// <summary>
        /// btnPrijava control.

        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>

        protected global::System.Web.UI.WebControls.Button btnRegister;

        protected global::System.Web.UI.WebControls.Button btnPrijava;

    }
}
